### ISSUE TITLE
error starting index.js

### ISSUE THREAD

**Issue by wroekel** [alimalkhalifa/conanmanager#1]
Hello,

Was trying to test you're manager but getting the following error. 
module.js:471
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Conan\conanmanager\store.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by alimalkhalifa** [comment]
Hi wroekel, thanks for flagging this issue.
I made a mistake in the readme instructions.

I have updated that.

Please use these commands:
````
git clone https://github.com/alimalkhalifa/conanmanager.git
cd conanmanager
npm install
npm start
````

**Comment by wroekel** [comment]
thank you for the fast update. Will try it out right now.
